#### calculated the enthalpic and entropic contributions to the binding free energy by MM/PB(GBSA) and NMA, respectively.
#### please specify the path of MMPBSA.py@AmberTools
#### Inputs: (1) *.mdcrd (mdcrd file, Amber format, extracted from Amber/Gromacs trajectory)
#### Inputs: (2) *.prmtop (Complex/Receptor/Ligand topology file, Amber format, generated by tleap@Amber)
#### Inputs: (3) mmpbsa_paperjcc.in (parameters for MM/PBSA calculation ) or entropy_paperjcc.in (parameters for NMA calculation )
#### Outputs: FINAL_RESULTS_MMPBSA.dat or Entropy-NMA-20-result.dat (final output file)
#### See http://ambermd.org/tutorials/advanced/tutorial3/py_script/index.htm for more details.

MMPBSA.py -O -i ../mmpbsa_paperjcc.in -o FINAL_RESULTS_MMPBSA.dat -cp  ../com.prmtop  -rp ../rec.prmtop -lp ../lig.prmtop -y complex-*.mdcrd
MMPBSA.py -O -i ../entropy_paperjcc.in  -o Entropy-NMA-20-result.dat  -cp  ../com.prmtop  -rp ../rec.prmtop -lp ../lig.prmtop -y entropy*.mdcrd